# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='text',
            field=models.TextField(default='SOME STRING', verbose_name='text'),
        ),
    ]
