# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-08 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20181208_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['upload_date']},
        ),
        migrations.AddField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='등록 일시'),
            preserve_default=False,
        ),
    ]
