# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-08 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20181208_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일시'),
        ),
    ]
